# Generated by Django 3.0.2 on 2020-02-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20200227_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_template',
            field=models.TextField(blank=True, verbose_name='Email Template'),
        ),
    ]
