# Generated by Django 3.0.2 on 2020-02-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_company_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
