# Generated by Django 3.0.2 on 2020-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='end_date',
            field=models.DateField(default='03/03/2020'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='start_date',
            field=models.DateField(default='03/03/2020'),
        ),
    ]
